// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables or fallback to the previous values
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://hayrbdzsglfmidwrlawu.supabase.co";
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhheXJiZHpzZ2xmbWlkd3JsYXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NzYwNjcsImV4cCI6MjA1OTA1MjA2N30.AfBRE4xY4TIMWndtxnXyyOqlV9l8BpNHbTHeZbVXpxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);